/**
 * Standardized Architectural Furniture Catalog
 * Contains dimensions (in feet), room type tags, and 3D bounding attributes.
 */

export const FURNITURE_CATEGORIES = {
  BEDROOM: 'bedroom',
  LIVING: 'living',
  DINING: 'dining',
  KITCHEN: 'kitchen',
  BATHROOM: 'bathroom',
  ENTRY_POOJA: 'entry_pooja',
};

export const FURNITURE_CATALOG = [
  // --- Bedroom ---
  {
    type: 'bed_king',
    label: 'King Bed & Pillows',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 6.5,
    length: 6.5,
    height: 3.0,
    roomTypes: ['master_bedroom', 'bedroom'],
    description: '6.5×6.5 ft king bed with dual headboard pillows',
  },
  {
    type: 'bed_queen',
    label: 'Queen Bed',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 5.0,
    length: 6.5,
    height: 2.8,
    roomTypes: ['bedroom', 'guest_bedroom', 'master_bedroom'],
    description: '5×6.5 ft standard double queen bed',
  },
  {
    type: 'bed_single',
    label: 'Single Bed',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 3.5,
    length: 6.5,
    height: 2.5,
    roomTypes: ['bedroom', 'guest_bedroom'],
    description: '3.5×6.5 ft single bed',
  },
  {
    type: 'nightstand',
    label: 'Nightstand Table',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 1.5,
    length: 1.5,
    height: 2.0,
    roomTypes: ['master_bedroom', 'bedroom', 'guest_bedroom'],
    description: 'Bedside lamp nightstand',
  },
  {
    type: 'wardrobe',
    label: 'Built-in Wardrobe',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 5.0,
    length: 2.0,
    height: 7.0,
    roomTypes: ['master_bedroom', 'bedroom', 'guest_bedroom'],
    description: 'Full-height 2-ft deep wardrobe closet',
  },
  {
    type: 'study_desk',
    label: 'Study Desk & Chair',
    category: FURNITURE_CATEGORIES.BEDROOM,
    width: 4.0,
    length: 2.0,
    height: 2.5,
    roomTypes: ['bedroom', 'master_bedroom', 'living'],
    description: 'Work desk with ergonomic task chair',
  },

  // --- Living ---
  {
    type: 'sofa_3seater',
    label: '3-Seater Sofa Couch',
    category: FURNITURE_CATEGORIES.LIVING,
    width: 7.0,
    length: 3.0,
    height: 2.8,
    roomTypes: ['living'],
    description: 'Spacious 3-seater living room sofa',
  },
  {
    type: 'sofa_lshape',
    label: 'L-Shape Sectional Sofa',
    category: FURNITURE_CATEGORIES.LIVING,
    width: 8.0,
    length: 6.5,
    height: 2.8,
    roomTypes: ['living'],
    description: 'Corner lounge sectional sofa',
  },
  {
    type: 'coffee_table',
    label: 'Coffee Table',
    category: FURNITURE_CATEGORIES.LIVING,
    width: 3.5,
    length: 2.0,
    height: 1.5,
    roomTypes: ['living'],
    description: 'Low central living coffee table',
  },
  {
    type: 'tv_unit',
    label: 'TV Media Console',
    category: FURNITURE_CATEGORIES.LIVING,
    width: 5.5,
    length: 1.5,
    height: 2.0,
    roomTypes: ['living', 'master_bedroom'],
    description: 'Wall-mounted or freestanding entertainment console',
  },
  {
    type: 'armchair',
    label: 'Accent Armchair',
    category: FURNITURE_CATEGORIES.LIVING,
    width: 2.5,
    length: 2.5,
    height: 2.8,
    roomTypes: ['living', 'bedroom', 'balcony'],
    description: 'Comfortable lounge armchair',
  },

  // --- Dining ---
  {
    type: 'dining_6seater',
    label: '6-Seater Dining Set',
    category: FURNITURE_CATEGORIES.DINING,
    width: 5.5,
    length: 3.5,
    height: 2.5,
    roomTypes: ['dining', 'living'],
    description: 'Rectangular dining table with 6 chairs',
  },
  {
    type: 'dining_4seater',
    label: '4-Seater Dining Set',
    category: FURNITURE_CATEGORIES.DINING,
    width: 4.0,
    length: 3.0,
    height: 2.5,
    roomTypes: ['dining', 'living', 'kitchen'],
    description: 'Compact 4-seater dining set',
  },

  // --- Kitchen & Utility ---
  {
    type: 'kitchen_counter_l',
    label: 'L-Shape Countertop & Sink',
    category: FURNITURE_CATEGORIES.KITCHEN,
    width: 7.0,
    length: 5.0,
    height: 2.8,
    roomTypes: ['kitchen'],
    description: 'Granite L-shaped cooking & preparation counter',
  },
  {
    type: 'refrigerator',
    label: 'Double-Door Fridge',
    category: FURNITURE_CATEGORIES.KITCHEN,
    width: 2.5,
    length: 2.5,
    height: 5.8,
    roomTypes: ['kitchen', 'utility'],
    description: 'Kitchen refrigerator unit',
  },
  {
    type: 'gas_hob',
    label: 'Gas Hob Stove',
    category: FURNITURE_CATEGORIES.KITCHEN,
    width: 2.5,
    length: 1.8,
    height: 0.5,
    roomTypes: ['kitchen'],
    description: '3-burner gas stove cooktop',
  },
  {
    type: 'washing_machine',
    label: 'Washing Machine',
    category: FURNITURE_CATEGORIES.KITCHEN,
    width: 2.0,
    length: 2.0,
    height: 2.8,
    roomTypes: ['utility', 'bathroom'],
    description: 'Front-load washing machine unit',
  },

  // --- Bathroom ---
  {
    type: 'toilet_wc',
    label: 'Water Closet (WC)',
    category: FURNITURE_CATEGORIES.BATHROOM,
    width: 2.2,
    length: 1.5,
    height: 2.5,
    roomTypes: ['bathroom', 'attached_bathroom'],
    description: 'Wall-hung commode with cistern',
  },
  {
    type: 'vanity_sink',
    label: 'Vanity Washbasin & Mirror',
    category: FURNITURE_CATEGORIES.BATHROOM,
    width: 2.5,
    length: 1.8,
    height: 2.8,
    roomTypes: ['bathroom', 'attached_bathroom', 'dining'],
    description: 'Wash basin counter unit',
  },
  {
    type: 'shower_cubicle',
    label: 'Glass Shower Enclosure',
    category: FURNITURE_CATEGORIES.BATHROOM,
    width: 3.0,
    length: 3.0,
    height: 6.5,
    roomTypes: ['bathroom', 'attached_bathroom'],
    description: 'Walk-in shower enclosure with drain',
  },

  // --- Pooja & Entry ---
  {
    type: 'pooja_mandir',
    label: 'Pooja Mandir Alter',
    category: FURNITURE_CATEGORIES.ENTRY_POOJA,
    width: 3.0,
    length: 2.0,
    height: 4.5,
    roomTypes: ['pooja', 'living'],
    description: 'Wooden devotional prayer shrine',
  },
  {
    type: 'shoe_rack',
    label: 'Entry Shoe Console',
    category: FURNITURE_CATEGORIES.ENTRY_POOJA,
    width: 3.0,
    length: 1.2,
    height: 2.5,
    roomTypes: ['foyer', 'parking', 'living'],
    description: 'Entrance foyer shoe storage',
  },
];

export const getFurnitureDefinition = (type) => {
  return FURNITURE_CATALOG.find((item) => item.type === type) || null;
};
